#!/usr/bin/env bash

# Print ZFS filesystem user disk quotas in a format similar to Linux "repquota".
# ZFS has no concept of soft quota limits.

if [[ $# -gt 0 ]]
then
	username=$1
else
	username=$USER
fi

echo "ZFS filesystem quota for user $username"
/usr/local/bin/zfsrepquota -u $username
